package com.trafiklab.trafiklab;

import com.trafiklab.trafiklab.classes.Line;
import com.trafiklab.trafiklab.controllers.LinesController;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.ArrayList;
import java.util.List;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class TrafiklabApplication {

	public static void main(String[] args)
	{
		List<Line> Lines = new ArrayList<>();
		SpringApplication.run(TrafiklabApplication.class, args);
		LinesController controller = new LinesController();
		Lines = controller.getBiggestLines();

		System.out.println(controller.PrettyPrintConsole(Lines));
	}

}
